---
- hosts: linux_servers
  become: true

  #! Handler voor de restart van de sshd service.
  handlers:
    - name: Restart SSH service.
      service: name=sshd state=restarted

  tasks:
    # Add windows server to a domein
    - name: Join to domain
      win_domain_membership:
        dns_domain_name: tycho.local
        hostname: mydomainclient
        domain_admin_user: "{{ win_domain_admin_user }}"
        domain_admin_password: "{{ win_domain_admin_password }}"
        domain_ou_path: "OU=Windows,OU=Servers,DC=tycho,DC=local"
        state: domain
      register: domain_state
    
    - name: set group with delete protection enabled
      win_domain_group:
        name: Users
        scope: domainlocal
        category: security
        ignore_protection: no

      - name: Install security updates
        win_updates:
          category_names:
            - SecurityUpdates
          Notify: reboot windows system

      – name: Install missing updates
         win_updates:
           Category_names:
              – ServicePacks
              – UpdateRollups        
              – CriticalUpdates
           Reboot: yes
